/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/Pencil.glb -o src/components/models/Pencil.jsx -r public
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pencil(props) {
  const { nodes, materials } = useGLTF(process.env.REACT_APP_REPOSITORY+'/models/Pencil.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Pencil1_1.geometry} material={materials.Ferrule1Pencil1} />
        <mesh geometry={nodes.Pencil1_2.geometry} material={materials.Eraser1Pencil1} />
        <mesh geometry={nodes.Pencil1_3.geometry} material={materials.Wood1Pencil1} />
        <mesh geometry={nodes.Pencil1_4.geometry} material={materials.Lead1Pencil1} />
      </group>
    </group>
  )
}

useGLTF.preload(process.env.REACT_APP_REPOSITORY+'/models/Pencil.glb')
