/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\one_ring.glb -o src/components/models/ring.jsx -r public 
Author: VirtualBG (https://sketchfab.com/undereality)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/one-ring-247159eef183450a81887b569ba838c9
Title: One Ring
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ring(props) {
  const { nodes, materials } = useGLTF('/models/one_ring.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['08___Default']} position={[3.056, 3.056, 0]} rotation={[-Math.PI, -Math.PI / 2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/one_ring.glb')
